version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pokemon_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - db
    networks:
      - pokemon_network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jonhdoe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: StrongPassword
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - pokemon_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - pokemon_network

  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://ash:password@db:5432/pokemon_db?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - pokemon_network
  loader:
    build: .
    depends_on:
      - db
    networks:
      - pokemon_network

volumes:
  postgres_data:
  grafana_data:
  pgadmin-data:
  prometheus_data:

networks:
  pokemon_network:
    driver: bridge
